# Generated by Django 5.1.15 on 2026-08-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lsas', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_start', models.DateTimeField(db_index=True)),
                ('session_end', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('lsa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lsas.lsaprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='parents.parent')),
            ],
            options={
                'ordering': ['-session_start'],
                'indexes': [models.Index(fields=['lsa', 'session_start', 'session_end'], name='bookings_bo_lsa_id_6d0ce2_idx')],
            },
        ),
    ]
